# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
install_os_packages: true
disable_firewall: false
disable_selinux: true
firewall_service: "{% if ansible_distribution_major_version | int == 6 %}iptables{% elif ansible_distribution_major_version | int >= 7 %}firewalld{% else %}0{% endif %}"

package_repository_files:
  - "redhat.repo"
  - "rh-cloud.repo"
  - "oracle-linux-ol7.repo"
  - "oracle-linux-ol8.repo"
  - "oracle-linux-ol9.repo"

oracle_required_rpms:
  - bc
  - bind-utils
  - binutils
  - ethtool
  - firewalld
  - glibc
  - glibc-devel
  - initscripts
  - ksh
  - libaio
  - libaio-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libXi
  - libXtst
  - make
  - module-init-tools
  - net-tools
  - nfs-utils
  - openssh-clients
  - pam
  - perl  # OS perl is required for OJVM patching as per MOS note 2978451.1
  - procps
  - psmisc
  - smartmontools
  - sysstat
  - tar
  - unzip
  - util-linux-ng
  - xorg-x11-utils
  - xorg-x11-xauth

oracle_required_rpms_el7:
  - compat-libcap1
  - compat-libstdc++-33
  - gcc
  - gcc-c++
  - policycoreutils-python

oracle_required_rpms_el8:
  - compat-openssl10
  - elfutils-libelf
  - fontconfig
  - libasan
  - libibverbs
  - liblsan
  - libnsl
  - librdmacm
  - libX11
  - libXau
  - libxcb
  - libXrender
  - openssl-libs
  - policycoreutils
  - policycoreutils-python-utils

oracle_required_rpms_el9:
  - compat-openssl11
  - elfutils-libelf
  - fontconfig
  - glibc-headers
  - grub2-tools
  - libasan
  - libibverbs
  - liblsan
  - libnsl
  - libnsl2
  - librdmacm
  - libvirt-libs
  - libX11
  - libXau
  - libxcb
  - libxcrypt-compat
  - libXrender
  - policycoreutils
  - policycoreutils-python-utils

# Set parameter for kernel shared memory segments, related to but independent from memory_pct which is used to calculate SGA_TARGET:
#   - If memory_pct is set and is less than 50 percent, then use 50 percent
#   - If memory_pct is set and is 50 percent or more, then use memory_pct
#   - If memory_pct is not defined, use 65 percent
ram_pct_used: "{{ (50 if memory_pct is defined and memory_pct < 50 else memory_pct) if memory_pct is defined else 65 }}"

# Kernel parameters to check and report on pre-adjustment values when verbosity=1:
sysctl_params:
  - kernel.sem
  - kernel.shmall
  - kernel.shmmax
  - kernel.shmmni
  - kernel.panic_on_oops
  - kernel.panic
  - fs.file-max
  - fs.aio-max-nr
  - net.ipv4.ip_local_port_range
  - net.core.rmem_default
  - net.core.rmem_max
  - net.core.wmem_default
  - net.core.wmem_max

# Kernel parameters to set:
sysctl_param_values:
  - parameter: "kernel.sem"
    value: "250 32000 100 128"
  - parameter: "kernel.shmmax"
    value: "{{ (ansible_memtotal_mb * 524288) | round(0,'ceil') | int }}"  # (MB->Bytes)/2: 1024*1024/2 = 52488
  - parameter: "kernel.shmmni"
    value: 4096
  - parameter: "kernel.panic_on_oops"
    value: 1
  - parameter: "kernel.panic"
    value: 10
  - parameter: "fs.file-max"
    value: 6815744
  - parameter: "fs.aio-max-nr"
    value: 1048576
  - parameter: "net.ipv4.ip_local_port_range"
    value: "9000 65535"
  - parameter: "net.core.rmem_default"
    value: 262144
  - parameter: "net.core.rmem_max"
    value: 4194304
  - parameter: "net.core.wmem_default"
    value: 262144
  - parameter: "net.core.wmem_max"
    value: 1048576

resource_limits:
  - name: nofile
    type: soft
    value: "1024"
  - name: nofile
    type: hard
    value: "65536"
  - name: nproc
    type: soft
    value: "2047"
  - name: nproc
    type: hard
    value: "16384"
  - name: stack
    type: soft
    value: "10240"
  - name: stack
    type: hard
    value: "32768"
  - name: memlock
    type: soft
    value: "unlimited"
  - name: memlock
    type: hard
    value: "unlimited"

oracleasm_libs:
  - kmod-oracleasm
  - http://download.oracle.com/otn_software/asmlib/oracleasmlib-2.0.12-1.el7.x86_64.rpm
  - https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracleasm-support-2.1.11-2.el7.x86_64.rpm
