  - name: asm-create | write pfile
    template:
      src: init.ora.j2
      dest: "{{ grid_home }}/dbs/init{{ asm_sid }}.ora"
    become: yes
    become_user: "{{ grid_user }}"
    tags: gi-setup,start-asm

  - name: Change asm lv permissions
    file:
      path: "{{ item.1.blk_device }}"
      state: link
      mode: '0660'
      owner: "{{ grid_user }}"
      group: asmdba
    when: "'mapper' in item.1.blk_device"
    with_subelements:
      - "{{ asm_disks }}"
      - disks

  - name: asm-create | start asm instance
    shell: |
      set -o pipefail
      ${ORACLE_HOME}/bin/srvctl add asm -d '{{ asm_diskstring }}'
      ${ORACLE_HOME}/bin/srvctl start asm
      echo "create spfile from pfile;" | sqlplus -s / as sysasm
      ${ORACLE_HOME}/bin/srvctl stop asm
      ${ORACLE_HOME}/bin/srvctl start asm
    environment:
      ORACLE_HOME: "{{ grid_home }}"
      PATH: "{{ grid_home }}/bin:${PATH}"
      ORACLE_SID: "{{ asm_sid }}"
      LD_LIBRARY_PATH: "{{ grid_home }}/lib:${LD_LIBRARY_PATH}"
    register: start_asm
    become: yes
    become_user: "{{ grid_user }}"
    tags: gi-setup,start-asm

  - name: asm-create | start asm ouput
    debug:
      msg: "{{ start_asm }}"
      verbosity: 1
    tags: gi-setup,start-asm

  - name: asm-create | (asmlib) Create disk groups
    shell: |
      set -o pipefail
      echo "
      CREATE DISKGROUP {{ item.diskgroup }} EXTERNAL REDUNDANCY
      {% for i in item.disks %}  DISK 'ORCL:{{ i.name }}'
      {% endfor %}
      ATTRIBUTE
         'compatible.asm'   = '{{ diskgroup_compatible_asm }}',
         'compatible.rdbms' = '{{ diskgroup_compatible_rdbms }}';
      ;
      " | sqlplus -s / as sysasm
    environment:
      ORACLE_HOME: "{{ grid_home }}"
      PATH: "{{ grid_home }}/bin:${PATH}"
      ORACLE_VERSION: "{{ oracle_ver }}"
      ORACLE_SID: "{{ asm_sid }}"
      LD_LIBRARY_PATH: "{{ grid_home }}/lib:${LD_LIBRARY_PATH}"
    when: asm_disk_control == "asmlib" or (asm_disks | join(' ') is search('mapper'))
    with_items:
      - "{{ asm_disks }}"
    register: create_dg
    failed_when: "'ERROR' in create_dg.stdout"
    become: yes
    become_user: "{{ grid_user }}"
    tags: gi-setup,start-asm

  - name: asm-create | (udev) Create disk groups
    shell: |
      set -o pipefail
      echo "
      CREATE DISKGROUP {{ item.diskgroup }} EXTERNAL REDUNDANCY
      {% for i in item.disks %}  DISK '/dev/oracleasm/{{ i.name }}'
      {% endfor %}
      ATTRIBUTE
         'compatible.asm'   = '{{ diskgroup_compatible_asm }}',
         'compatible.rdbms' = '{{ diskgroup_compatible_rdbms }}';
      ;
      " | sqlplus -s / as sysasm
    environment:
      ORACLE_HOME: "{{ grid_home }}"
      PATH: "{{ grid_home }}/bin:${PATH}"
      ORACLE_VERSION: "{{ oracle_ver }}"
      ORACLE_SID: "{{ asm_sid }}"
      LD_LIBRARY_PATH: "{{ grid_home }}/lib:${LD_LIBRARY_PATH}"
    when: asm_disk_control == "udev" and not (asm_disks | join(' ') is search('mapper'))
    with_items:
      - "{{ asm_disks }}"
    register: create_dg
    failed_when: "'ERROR' in create_dg.stdout"
    become: yes
    become_user: "{{ grid_user }}"
    tags: gi-setup,start-asm

  - name: asm-create | debug asm disk group creation
    debug:
      msg: "{{ create_dg }}"
      verbosity: 1
    tags: gi-setup,start-asm
