---

  asm_diskstring: "{% if asm_disks | join(' ') is search('mapper') %}ORCL:*{% elif asm_disk_management == 'asmlib' and ansible_distribution == 'OracleLinux' %}ORCL:*{% else %}/dev/oracleasm/*{% endif %}"

  diskgroup_compatible_asm: "{{ oracle_ver }}"
# Set to 11.2.0.1.0 for >=2TB LUNs
  diskgroup_compatible_rdbms: "11.2.0.4.0"

  run_cluvfy: false

  gi_software:
    - name: 19c_gi
      version: 19.3.0.0.0
      files:
        - "V982068-01.zip"
      sha256sum:
        - "D668002664D9399CF61EB03C0D1E3687121FC890B1DDD50B35DCBE13C5307D2E"
    - name: 18c_gi
      version: 18.0.0.0.0
      files:
        - "V978971-01.zip"
      sha256sum:
        - "122C1A780FE0C399818064021E3D797ED4C6B3BB68CEB2E102430FA370054CD1"
    - name: 12201_gi
      version: 12.2.0.1.0
      files:
        - "V840012-01.zip"
      sha256sum:
        - "E8BF36092F7600411A63AAA79CD4F816FB96BB3CFFA66746832416DD2FF11B15"
    - name: 12102_gi
      version: 12.1.0.2.0
      files:
        - "V46096-01_1of2.zip"
        - "V46096-01_2of2.zip"
      sha256sum:
        - "09B4B51A60D6913B82E3353EEF179969AD0968FF8ACFB37CA891F04DF67B93F0"
        - "C59B8ADA602048AF62AD8F3621F476BE225A782A8CE7BC55B2825E58157AC070"
    - name: 11204_gi
      version: 11.2.0.4.0
      files:
        - "p13390677_112040_Linux-x86-64_3of7.zip"
      sha256sum:
        - "09C08AD3E1EE03DB1707F01C6221C7E3E75EC295316D0046CC5D82A65C7B928C"
