title: bms-toolkit
description: Toolkit for installing and creating an initial database on Bare Metal Solution
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
