# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: nfs | Install NFS mount utility
  become: true
  become_user: root
  package:
    name: nfs-utils
    state: present
    lock_timeout: "{{ dnf_lock_timeout }}"
  when: ansible_os_family == "RedHat"

- name: nfs | Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: nfs | Mount NFS share (swlib)
  become: true
  become_user: root
  mount:
    fstype: nfs
    name: "{{ swlib_path }}"
    opts: "vers=4,_netdev,rsize=8192,wsize=8192,timeo=14,intr,user"
    src: "{{ swlib_mount_src }}"
    state: mounted
